### PR TITLE
test: Jest testing of front/backend

### PR DESCRIPTION
**Pull request by NickyMeuleman**
This should run all tests (frontend and backend), label them as they run and collect coverage information.

#### To check it out run `yarn test` in the root of the project.

I initialized the coverage tresholds to be 0%.

To do is add the `"collectCoverageFrom"` key to the `jest.config.js` in the root of the project. It only collects coverage for files that are being tested right now.
That collectCoverageFrom follows the glob pattern, anyone good with that? The backend was fairly simple since it had an `src` folder with all files that needed to be tested inside it.

### CODE REVIEW

**Comment by NickyMeuleman** [comment]
build probably failing because of `.babelrc` in backend.
Can't investigate now, but should be a straightforward fix. (object-spread not being picked up?)

**Comment by pantharshit00** [comment]
Upgrade babel to v7

**Comment by NickyMeuleman** [comment]
Removed the `modules: false` part of babel.
Keeping it in the `.js` form and adding a `babel: {"preset": "./.babelrc"}` part in `package.json` caused an error on test run: `Multiple configuration files found. Please remove one:
     - .babelrc.js
     - package.json`

Going to update to babel 7 in seperate commit and if it fixes this make the neccessary changes.

**Comment by pantharshit00** [comment]
I am doing the babel upgrade currently. If successful will push to this PR.

**Pull request merged**
